### ISSUE TITLE
Confluence: Authorization/Authentication code

### ISSUE THREAD

**Issue by tjav** [tjav/confluence-azure-func#2]
💡 Summary
Write a script that automates the authentication to Confluence.

🛠 Implementation Details
Authentication can be via bearer or python library

✏️ Additional Information
part of the confluence content retrieval solution
![image](https://user-images.githubusercontent.com/15814300/156530167-7785cd43-b6cb-40da-9d62-cfef93066bfa.png)

✔️Acceptance Criteria
- script could automatically authenticate to conlfuence api
- Secrets are stored in a key vault

**Comment by humak** [comment]
hi Tim, pushed a code for authentication and getting the 'product catalog' table, but not automated.
